add simplified ci config

diff --git a/.github/workflows/nextflow-linter.yaml b/.github/workflows/nextflow-linter.yaml
--- a/.github/workflows/nextflow-linter.yaml
+++ b/.github/workflows/nextflow-linter.yaml
@@ -32,4 +32,4 @@ jobs:
         run: nextflow -version
 
       - name: check syntax in main.nf
-        run: nextflow main.nf -preview || (echo "Syntax check failed. Please review the error message above." && exit 1)
+        run: nextflow main.nf -c .github/workflows/ci.config -preview || (echo "Syntax check failed. Please review the error message above." && exit 1)
